### ISSUE TITLE
Missing `token` attribute in magic link create response

### ISSUE THREAD

**Issue by alikirec** [stytchauth/stytch-python#112]
In https://github.com/stytchauth/stytch-python/blob/main/stytch/models/magic_links.py#L15, although `token` is listed in function doc, it's not listed in attributes. As we use embeddable magic links, that prevents us from migrating to the latest version.

**Comment by logan-stytch** [comment]
Thanks for the report on the missing attribute. I'll have that fixed ASAP and deployed as 6.2.2
