### ISSUE TITLE
Authenticating with an expired OTP gives you a bad error message

### ISSUE THREAD

**Issue by jakemagner-alation** [stytchauth/stytch-python#43]
If you call client.otps.authenticate with an expired code it tells you that your project ID or key is invalid and hides the actual error message about the OTP code being invalid

https://github.com/stytchauth/stytch-python/blob/56f59bddb2cc76577e1fd195665eb8e73f8c5d4a/stytch/api/decorator.py#L11

**Comment by nikhil-stytch** [comment]
Thank you for opening up the issue, Jake! We've fixed this in our [v4.3.1 update](https://github.com/stytchauth/stytch-python/releases/tag/v4.3.1)
