### ISSUE TITLE
Async support?

### ISSUE THREAD

**Issue by paolodina** [stytchauth/stytch-python#89]
Hi, I'm using stytch-python in a FastAPI project, with the following issue. Any chance to add async support to the library?

```python
@router.post("/login", status_code=201, response_model=LoginOrCreateOut)
async def login_or_create(
    data: LoginOrCreateIn,
    session: AsyncSession = Depends(db_session),
    ) -> None:

   resp = await client.magic_links.email.login_or_create(email=data.user_email)

   # Now I'll use the `AsyncSession` object to eventually create the user.
   ...
```
Exception:

```bash
  File "/some/path/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/some/path/project/api/auth/views.py", line 92, in login_or_create
    resp = await client.magic_links.email.login_or_create(email=user_email)
TypeError: object Response can't be used in 'await' expression
```

**Comment by chris-stytch** [comment]
Heya @paolodina , we don't have any current plans to offer async within `stytch-python`.

Thanks for the suggestion, we'll go ahead and leave this open to gather feedback and interest from other folks using `stytch-python`.

**Comment by chris-stytch** [comment]
Current state of work on async in `stytch-python` is tracked in the following PR: https://github.com/stytchauth/stytch-python/pull/95

**Comment by paolodina** [comment]
thanks!

**Comment by chris-stytch** [comment]
Closing this out as completed by [v6.0.0](https://github.com/stytchauth/stytch-python/releases/tag/v6.0.0) of our `stytch-python` library. Note this is a breaking change from v5.X.X.
